### ISSUE TITLE
No funciona el acceso directo a un proyecto

### ISSUE THREAD

**Issue by martinszy** [hhba/towlandia#3]
Me reportaron este error y lo documento aquí.

Pasos para reproducir:
1. Acceder a decada votada
2. Acceder al archivo
3. Hacer click en cualquiera de los enlaces que dicen "votación"

Resultado: Carga año y fecha, pero no muestra el expediente ni las votaciones.

Resltado esperado: Muestra el expediente y las votaciones.

No aparece ningún error javascript.

**Comment by lucianoamor** [comment]
con firefox (38.0.5, win7) y chrome (43.0.2357.130 m, win7) el error no lo pude reproducir: funciona correctamente. sería bueno probar otros navegadores y entornos.

**Comment by andytow** [comment]
Se trata de un error en la tabla.

El 25/06/2015 a las 12:57 a.m., Martín Szyszlican escibió:

**Comment by andytow** [comment]
ARREGLADO

El 25/06/2015 a las 12:57 a.m., Martín Szyszlican escibió:
