### ISSUE TITLE
Enlaces a la otra cámara

### ISSUE THREAD

**Issue by martinszy** [hhba/towlandia#4]
Recibo un mail que dice: "sugeriría que en algún lado o de alguna forma se advierta al usuario que si no encuentra la ley desde diputados, la busque desde senadores. Creo que no todos tienen conocimiento de que las causas pueden ingresar por cualquiera de los recintos, o cuál es la razón por la que la web te recibe pidiendo que elijas entre uno de ellos."

No hay forma de ir de diputados a senadores y viceversa una vez que uno ya eligió.
Sería de lujo que se pueda vincular _a la misma ley_ en la otra cámara, pero con agregar un enlace simple ya mejora.

**Comment by lucianoamor** [comment]
en el pie, columna *Secciones*, hay un link para pasar a la otra cámara.

**Comment by martinszy** [comment]
Ok, quizás hacerlo más prominente?

Hablo de parte de un usuario que tuvo problemas en descubrir que podía
buscar le proyecto en la otra cámara, por su falta de conocimiento del
funcionamiento del congreso, a pesar de estar investigando estos temas.

Entiendo que esta aplicación es más para especialistas, y antes no hubiera
planteado este tipo de requerimientos, pero tenemos que tener en cuenta el
tipo de gente que la está usando ahora.

Saludos!

2015-06-25 10:40 GMT-03:00 lucianoamor <notifications@github.com>:

> en el pie, columna *Secciones*, hay un link para pasar a la otra cámara.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hhba/towlandia/issues/4#issuecomment-115261255>.
>



-- 
*Martín Szyszlican*
Desarrollo web usable y accesible
martinszyszlican.com

**Comment by andytow** [comment]
Abajo en http://www.decadavotada.com.ar/index-d.html y 
http://www.decadavotada.com.ar/index-s.html hay enlace a la otra Camara.

El 25/06/2015 a las 12:59 a.m., Martín Szyszlican escibió:

**Comment by andytow** [comment]
No veo que les cueste mucho volver al inicio y elegir Senadores.

El 25/06/2015 a las 10:53 a.m., Martín Szyszlican escibió:

**Comment by martinszy** [comment]
Ok, ¿Y lo de linkear al mismo proyecto en la otra cámara? ¿Se puede eso?

**Comment by andytow** [comment]
Posible pero bastante dificil lo veo.

On Fri, 26 Jun 2015 09:54:30 -0700, Martín Szyszlican wrote
