### ISSUE TITLE
API pública o acceso a la base de datos 

### ISSUE THREAD

**Issue by cactail** [hhba/towlandia#6]
Buenas, espero que alguien lea esto. 
Estoy haciendo una aplicación de análisis de Datos del Congreso Nacional y tengo problemas para conseguir los datos de votaciones del Senado.
Ustedes al parecer ya tienen parseados estos documentos.
Tienen la intención de publicar una API o acceso a la base de datos de decadavotoda?

Saludos

**Comment by lucianoamor** [comment]
Hola Francisco.
El que se encarga de conseguir, sistematizar y digitalizar los datos de las
votaciones es Andy Tow. Fijate de contactarlo acá:
https://twitter.com/andy_tow
Cuando se pueda ver algo de lo que estás haciendo, avisá.
Saludos,
Luciano
